name: Build and Push Image

on:
  push:
    branches:
      - dev

permissions:
  contents: read
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: projects/832245523839/locations/global/workloadIdentityPools/github-pool/providers/github-provider
          service_account: github-actions@ai-document-automation-498914.iam.gserviceaccount.com

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure Docker
        run: |
          gcloud auth configure-docker asia-south1-docker.pkg.dev --quiet

      - name: Build image
        run: |
          docker build -t asia-south1-docker.pkg.dev/ai-document-automation-498914/contract-demo-api/contract-demo-api:${{ github.sha }} .

      - name: Push image
        run: |
          docker push asia-south1-docker.pkg.dev/ai-document-automation-498914/contract-demo-api/contract-demo-api:${{ github.sha }}