name: Build and Push Image

on:
  push:
    branches:
      - dev
 
permissions:
  contents: read
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PROJECT_ID: ai-document-automation-498914
      REGION: asia-south1
      SERVICE_NAME: contract-demo-api
      REPOSITORY: contract-demo-api
      IMAGE_NAME: contract-demo-api

    steps:
      - uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: projects/832245523839/locations/global/workloadIdentityPools/github-pool/providers/github-provider
          service_account: contract-poc-sa@ai-document-automation-498914.iam.gserviceaccount.com

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure Docker
        run: |
          gcloud auth configure-docker asia-south1-docker.pkg.dev --quiet

      - name: Build image
        run: |
          docker build \
            -t $REGION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$IMAGE_NAME:${{ github.sha }} \
            .
      - name: Push image
        run: |
          docker push $REGION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$IMAGE_NAME:${{ github.sha }}

      - name: Deploy Cloud Run service
        run: |
          gcloud run deploy $SERVICE_NAME \
            --project=$PROJECT_ID \
            --region=$REGION \
            --image=$REGION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$IMAGE_NAME:${{ github.sha }} \
            --platform=managed \
            --allow-unauthenticated \
            --quiet
